//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CALC_DEMO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALCULATOR_TBL
    {
        public int IDCLC { get; set; }
        public Nullable<int> FST_NUMBER { get; set; }
        public Nullable<int> SND_NUMBER { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<int> RESULT { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
    }
}
